package drm.sel.showcase.controller;

import drm.sel.showcase.TestcontainersConfiguration;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@Sql("/sql/tasks_rest_controller/test_data.sql")
@Transactional
@SpringBootTest
@AutoConfigureMockMvc(printOnlyOnFailure = false)
@Import(TestcontainersConfiguration.class)
class TasksRestControllerIT {

    @Autowired
    MockMvc mockMvc;

    @Test
    void handleGetAllTasks_ReturnsValidResponseEntity() throws Exception {
        // given
        var requestBuilder = get("/api/tasks");

        // when
        this.mockMvc.perform(requestBuilder)
                // then
                .andExpectAll(
                        status().isOk(),
                        content().contentType(MediaType.APPLICATION_JSON),
                        content().json("""
                                [
                                    {
                                        "id": "b2715f0d-8459-4256-a8bc-078ceb6f04fd",
                                        "details": "Первая задача",
                                        "completed": false
                                    },
                                    {
                                        "id": "e2ac4591-51a0-424d-94a3-0b930201589f",
                                        "details": "Вторая задача",
                                        "completed": true
                                    }
                                ]
                                """)
                );
    }

    @Test
    void handleCreateTask_PayloadIsValid_ReturnsValidResponseEntity() throws Exception {
        // given
        var requestBuilder = post("/api/tasks")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                        {
                            "details": "Третья задача"
                        }
                        """);

        // when
        this.mockMvc.perform(requestBuilder)
                // then
                .andExpectAll(
                        status().isCreated(),
                        header().exists(HttpHeaders.LOCATION),
                        content().contentType(MediaType.APPLICATION_JSON),
                        content().json("""
                                {
                                    "details": "Третья задача",
                                    "completed": false
                                }
                                """),
                        // id is generated by the server, so we just check that it exists
                        jsonPath("$.id").exists()
                );
    }

    @Test
    void handleCreateTask_PayloadIsInvalid_ReturnsValidResponseEntity() throws Exception {
        // given
        var requestBuilder = post("/api/tasks")
                .contentType(MediaType.APPLICATION_JSON)
                .header(HttpHeaders.ACCEPT_LANGUAGE, "en-US")
                .content("""
                        {
                            "details": null
                        }
                        """);

        // when
        this.mockMvc.perform(requestBuilder)
                // then
                .andExpectAll(
                        status().isBadRequest(),
                        header().doesNotExist(HttpHeaders.LOCATION),
                        content().contentType(MediaType.APPLICATION_JSON),
                        // message from src/main/resources/messages.properties
                        content().json("""
                                {
                                    "errors": ["Task details must be set"]
                                }
                                """, true)
                );

    }

    @Test
    void handleGetTaskById_ReturnsValidResponseEntity() throws Exception {
        // given
        var id = UUID.fromString("b2715f0d-8459-4256-a8bc-078ceb6f04fd");
        var requestBuilder = get("/api/tasks/{id}", id);

        // when
        this.mockMvc.perform(requestBuilder)
                // then
                .andExpectAll(
                        status().isOk(),
                        content().contentType(MediaType.APPLICATION_JSON),
                        content().json("""
                                {
                                    "id": "b2715f0d-8459-4256-a8bc-078ceb6f04fd",
                                    "details": "Первая задача",
                                    "completed": false
                                }
                                """)
                );
    }

}